export const SET_SELECTED_PRODUCT_ITEM_ID = "SET_SELECTED_PRODUCT_ITEM_ID";
export const SET_SELECTED_SIZE_TO_CHECKOUT = "SET_SELECTED_SIZE_TO_CHECKOUT";
export const SET_CART_ITEMS_TO_CHECKOUT = "SET_CART_ITEMS_TO_CHECKOUT";
export const SET_IS_PRODUCT_OPEN = "SET_IS_PRODUCT_OPEN";
export const SET_SELECTED_QUANTITY = "SET_SELECTED_QUANTITY";